import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          <li>
            <Link href="/quickStart">Quick Start</Link>
          </li>
          <li>
            <Link href="/registerFields">Register Fields</Link>
          </li>
          <li>
            <Link href="/applyValidation">Apply Validation</Link>
          </li>
          <li>
            <Link href="/integratingAnExistingForm">
              Integrating An Existing Form
            </Link>
          </li>
          <li>
            <Link href="/integratingWithUILibraries">
              Integrating With UI Libraries
            </Link>
          </li>
          <li>
            <Link href="/integratingControlledInputs">
              Integrating Controlled Inputs
            </Link>
          </li>
          <li>
            <Link href="/handleErrors">Handle Errors</Link>
          </li>
          <li>
            <Link href="/schemaValidation">Schema Validation</Link>
          </li>
        </ul>

        <p>
          This Page is practice for{' '}
          <a href="https://react-hook-form.com/get-started/#Quickstart">
            https://react-hook-form.com/get-started/#Quickstart
          </a>
        </p>
      </main>
    </>
  )
}
